# Generated by Django 3.0.5 on 2020-05-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_blog_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cata',
            field=models.TextField(default='', null=True),
        ),
    ]
